# ------------------------------------------------------
# | ddddd   eeeee   ccccc   eeeee   bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | d   d   eeee    c       eeee    bbbbb   u   u |
# | d   d   e       c       e       b    b  u   u |
# | ddddd   eeeee   ccccc   eeeee   bbbbb   uuuuu |
# ------------------------------------------------------
# HomeSmartHome â€“ Docker-Stacks 
# File: stacks/unbound/docker-compose.yml
# Documentation: https://github.com/DaCeBu/docker-stacks
# Github Project: https://github.com/DaCeBu/docker-stacks.git
# Created by: DeCeBu (Data Excellence, Connectivity and Business)
# ------------------------------------------------------

services:
  unbound:
    image: mvance/unbound:latest
    container_name: unbound
    restart: unless-stopped
    ports:
      - "53:53/tcp"
      - "53:53/udp"
    volumes:
      - ./config:/opt/unbound/etc/unbound
    environment:
      - TZ=Europe/Berlin
